# Teste — Importação das bases Silver

Carrega os três parquets gerados em `data/1_silver/` para inspeção rápida.

In [81]:
import pandas as pd

from src.pipeline import (
    SILVER_ASSOCIADOS_PATH,
    SILVER_PRODUTOS_PATH,
    SILVER_MOVIMENTACAO_PATH,
    GOLD_FEATURES_PATH
)

associados = pd.read_parquet(SILVER_ASSOCIADOS_PATH)
produtos = pd.read_parquet(SILVER_PRODUTOS_PATH)
movimentacao = pd.read_parquet(SILVER_MOVIMENTACAO_PATH)

In [82]:
associados.shape, produtos.shape, movimentacao.shape

((1000, 7), (1000, 8), (1000, 7))

## Verificar Associados

In [83]:
associados.head()

,CHAVE,NOME,AGENCIA,CIDADE,DATA_ASSOCIACAO,RENDA_MENSAL,DATA_ASSOCIACAO_INVALIDA
0,1,Fernanda Sobrenome,1,Pato Branco,2023-11-03,14714.0,False
1,2,Carlos Sobrenome,2,Pato Branco,2020-11-06,20161.0,False
2,3,Bruno Sobrenome,4,Pato Branco,2018-05-01,23834.0,False
3,4,Juliana Sobrenome,4,Pato Branco,2020-07-09,24436.0,False
4,5,Amanda Sobrenome,5,Cascavel,2024-09-24,15961.0,False

### Validar Tipos dos Associados

In [84]:
associados.dtypes

CHAVE                                int64
NOME                                string
AGENCIA                              int64
CIDADE                              string
DATA_ASSOCIACAO             datetime64[us]
RENDA_MENSAL                       float64
DATA_ASSOCIACAO_INVALIDA              bool
dtype: object

### Validar Cidades

In [85]:
associados.CIDADE.unique()

<ArrowStringArray>
['Pato Branco', 'Cascavel', 'Toledo', 'Chapecó', 'Maringá']
Length: 5, dtype: string

### Validar Nulos

* Verificar as rendas mensais, avaliar outras base ou fontes para verificar a existencia de rendas mensais para os associados. Dependendo da utiliação ténicas de inserção, estimação de rendas podem ser utilizadas.

In [86]:
associados.isna().sum()

CHAVE                        0
NOME                         0
AGENCIA                      0
CIDADE                       0
DATA_ASSOCIACAO              0
RENDA_MENSAL                12
DATA_ASSOCIACAO_INVALIDA     0
dtype: int64

### Validas data futuras

* Avaliar datas em outras fonte e corrigir com data correta.

In [87]:
associados.loc[associados['DATA_ASSOCIACAO_INVALIDA']]

,CHAVE,NOME,AGENCIA,CIDADE,DATA_ASSOCIACAO,RENDA_MENSAL,DATA_ASSOCIACAO_INVALIDA
111,112,Bruno Sobrenome,2,Pato Branco,2026-11-22,17077.0,True
126,127,Ricardo Sobrenome,2,Toledo,2026-09-19,18496.0,True
144,145,Amanda Sobrenome,2,Toledo,2026-10-07,16441.0,True
156,157,Bruno Sobrenome,4,Pato Branco,2026-10-18,15271.0,True
158,159,Amanda Sobrenome,1,Maringá,2026-12-03,13889.0,True
173,174,Fernanda Sobrenome,3,Pato Branco,2026-11-28,11260.0,True
227,228,Joao Sobrenome,1,Maringá,2026-12-26,7248.0,True
256,257,Bruno Sobrenome,5,Pato Branco,2026-10-19,28012.0,True
264,265,Juliana Sobrenome,4,Cascavel,2026-12-05,7361.0,True
339,340,Fernanda Sobrenome,4,Pato Branco,2026-10-14,10900.0,True
357,358,Lucas Sobrenome,3,Toledo,2026-09-17,8099.0,True
368,369,Mariana Sobrenome,2,Toledo,2026-12-23,11330.0,True
385,386,Joao Sobrenome,5,Pato Branco,2026-11-13,10195.0,True
447,448,Fernanda Sobrenome,2,Pato Branco,2026-11-13,25094.0,True
464,465,Carlos Sobrenome,4,Maringá,2026-11-05,28190.0,True
485,486,Lucas Sobrenome,1,Pato Branco,2026-12-01,25450.0,True
516,517,Mariana Sobrenome,4,Chapecó,2026-10-07,4039.0,True
536,537,Bruno Sobrenome,2,Chapecó,2026-11-07,7422.0,True
547,548,Lucas Sobrenome,1,Chapecó,2026-10-27,22574.0,True
596,597,Juliana Sobrenome,1,Pato Branco,2026-10-07,27443.0,True
614,615,Joao Sobrenome,2,Cascavel,2026-10-19,25715.0,True
615,616,Carlos Sobrenome,1,Pato Branco,2026-10-04,NaN,True
672,673,Paula Sobrenome,3,Pato Branco,2026-10-08,25329.0,True
695,696,Paula Sobrenome,3,Cascavel,2026-11-03,14817.0,True
703,704,Fernanda Sobrenome,5,Cascavel,2026-10-23,23479.0,True
749,750,Lucas Sobrenome,3,Pato Branco,2026-11-11,29426.0,True
769,770,Mariana Sobrenome,5,Maringá,2026-09-18,NaN,True
772,773,Carlos Sobrenome,2,Pato Branco,2026-10-12,2883.0,True
773,774,Amanda Sobrenome,5,Chapecó,2026-12-14,19659.0,True
818,819,Amanda Sobrenome,1,Pato Branco,2026-12-19,27511.0,True
857,858,Mariana Sobrenome,5,Pato Branco,2026-11-04,24327.0,True
892,893,Juliana Sobrenome,2,Pato Branco,2026-11-07,9332.0,True
918,919,Bruno Sobrenome,2,Pato Branco,2026-11-13,18799.0,True
920,921,Paula Sobrenome,1,Pato Branco,2026-11-04,16100.0,True
927,928,Ricardo Sobrenome,5,Pato Branco,2026-12-26,5346.0,True
955,956,Juliana Sobrenome,2,Cascavel,2026-10-02,28364.0,True
998,999,Ricardo Sobrenome,3,Pato Branco,2026-12-17,16962.0,True

## Avaliar Produtos

In [88]:
produtos.head()

,CHAVE,CONTA_CORRENTE,CARTAO,CREDITO,INVESTIMENTO,CONSORCIO,SEGURO,QTD_PRODUTOS
0,1,True,True,True,False,False,False,3
1,2,True,True,True,False,False,False,3
2,3,False,False,True,False,True,False,2
3,4,False,True,True,False,True,False,3
4,5,True,True,False,False,False,True,3

In [89]:
produtos.dtypes

CHAVE             int64
CONTA_CORRENTE     bool
CARTAO             bool
CREDITO            bool
INVESTIMENTO       bool
CONSORCIO          bool
SEGURO             bool
QTD_PRODUTOS      int64
dtype: object

## AValiar Movimentação

In [90]:
movimentacao.head()

,CHAVE,SALDO_MEDIO,PIX_MENSAL,COMPRAS_CARTAO,SALDO_MEDIO_INVALIDO,PIX_MENSAL_INVALIDO,COMPRAS_CARTAO_INVALIDO
0,1,245843.0,55,1400.0,False,False,False
1,2,3031.0,43,19923.0,False,False,False
2,3,10181.0,95,7251.0,False,False,False
3,4,151001.0,53,19505.0,False,False,False
4,5,159737.0,50,6637.0,False,False,False

In [91]:
movimentacao.dtypes

CHAVE                        int64
SALDO_MEDIO                float64
PIX_MENSAL                   int64
COMPRAS_CARTAO             float64
SALDO_MEDIO_INVALIDO          bool
PIX_MENSAL_INVALIDO           bool
COMPRAS_CARTAO_INVALIDO       bool
dtype: object

## Avaliar duplicidade de chaves

In [92]:
# Integridade referencial entre as três entidades
chaves_associados = set(associados["CHAVE"])
chaves_produtos = set(produtos["CHAVE"])
chaves_movimentacao = set(movimentacao["CHAVE"])

chaves_associados == chaves_produtos == chaves_movimentacao

True

In [93]:
set(produtos["CHAVE"])

{1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000}

# Teste - Implementação de features

features = pd.read_parquet(SILVER_ASSOCIADOS_PATH)

In [94]:
import pandas as pd

pd.set_option("display.max_columns", None)

In [95]:
features = pd.read_parquet(GOLD_FEATURES_PATH)

In [96]:
features.head()

,CHAVE,NOME,AGENCIA,CIDADE,DATA_ASSOCIACAO,RENDA_MENSAL,DATA_ASSOCIACAO_INVALIDA,TEMPO_RELACIONAMENTO_DIAS,TEMPO_RELACIONAMENTO_ANOS,FAIXA_RENDA,CONTA_CORRENTE,CARTAO,CREDITO,INVESTIMENTO,CONSORCIO,SEGURO,QTD_PRODUTOS,INDICE_DIVERSIFICACAO,NIVEL_DIVERSIFICACAO,SALDO_MEDIO,PIX_MENSAL,COMPRAS_CARTAO,SALDO_MEDIO_INVALIDO,PIX_MENSAL_INVALIDO,COMPRAS_CARTAO_INVALIDO,NIVEL_SALDO_MEDIO,NIVEL_PIX_MENSAL,NIVEL_COMPRAS_CARTAO,NIVEL_MOVIMENTACAO,CLASSIFICACAO_TEMPO_INDISPONIVEL,SCORE_PRODUTOS,SCORE_RELACIONAMENTO,SCORE_SALDO,SCORE_UTILIZACAO,INDICE_CLASSIFICACAO,CLASSIFICACAO,FLAG_OPORTUNIDADE_ALTA_RENDA_POUCOS_PRODUTOS,FLAG_OPORTUNIDADE_BAIXA_UTILIZACAO,FLAG_OPORTUNIDADE_POTENCIAL_CRESCIMENTO
0,1,Fernanda Sobrenome,1,Pato Branco,2023-11-03,14714.0,False,1031,2.82,C - R$ 8.001 a R$ 15.000,True,True,True,False,False,False,3,0.5000,1 - Média,245843.0,55,1400.0,False,False,False,Alta,Média,Baixa,Alta,False,0.5115,0.3375,0.984,0.3060,0.5347,C - Maduro,False,False,False
1,2,Carlos Sobrenome,2,Pato Branco,2020-11-06,20161.0,False,2123,5.81,D - Acima de R$ 15.000,True,True,True,False,False,False,3,0.5000,1 - Média,3031.0,43,19923.0,False,False,False,Baixa,Média,Alta,Baixa,False,0.5115,0.661,0.012,0.7203,0.4762,B - Em Desenvolvimento,False,True,False
2,3,Bruno Sobrenome,4,Pato Branco,2018-05-01,23834.0,False,3043,8.33,D - Acima de R$ 15.000,False,False,True,False,True,False,2,0.3333,1 - Média,10181.0,95,7251.0,False,False,False,Baixa,Alta,Média,Baixa,False,0.2350,0.9616,0.046,0.6475,0.4725,B - Em Desenvolvimento,True,True,False
3,4,Juliana Sobrenome,4,Pato Branco,2020-07-09,24436.0,False,2243,6.14,D - Acima de R$ 15.000,False,True,True,False,True,False,3,0.5000,1 - Média,151001.0,53,19505.0,False,False,False,Média,Média,Alta,Média,False,0.5115,0.6906,0.612,0.7588,0.6432,D - Engajado,False,False,False
4,5,Amanda Sobrenome,5,Cascavel,2024-09-24,15961.0,False,705,1.93,D - Acima de R$ 15.000,True,True,False,False,False,True,3,0.5000,1 - Média,159737.0,50,6637.0,False,False,False,Média,Média,Baixa,Média,False,0.5115,0.2269,0.647,0.4202,0.4514,B - Em Desenvolvimento,False,False,False